const Homeproduct = 
[
    {
        id: 1,
        Name: 'product1',
        price: '3000',
        image: 'image/bluetooth.webp',
        cat: 'bluetooth',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '85000',
        image: 'image/tvv.jpg',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '5000',
        image: 'image/watchs.webp',
        cat: 'watch',
        type: 'featured',
    },
    {
        id: 4,
        Name: 'product4',
        price: '65000',
        image: 'image/mobile.jpg',
        cat: 'mobile',
        type: 'featured',
    },
    {
        id: 5,
        Name: 'product5',
        price: '800',
        image: 'image/earphone.webp',
        cat: 'earphone',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '2500',
        image: 'image/headset.jpg',
        cat: 'headphone',
        type: 'new',
    },
    {
        id: 7,
        Name: 'product7',
        price: '6000',
        image: 'image/btooth.jpg',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 8,
        Name: 'product8',
        price: '97000',
        image: 'image/lp.jpg',
        cat: 'laptop',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '86000',
        image: 'image/o1.png',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '76000',
        image: 'image/s1.avif',
        cat: 'mobile',
        type: 'new',
    },
    {
        id: 11,
        Name: 'product11',
        price: '45000',
        image: 'image/w2.webp',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: '85000',
        image: 'image/v1.jpg',
        cat: 'mobile',
        type: 'new',
    },
    {
        id: 13,
        Name: 'product13',
        price: '55000',
        image: 'image/time.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 14,
        Name: 'product14',
        price: '66000',
        image: 'image/o1.png',
        cat: 'mobile',
        type: 'featured',
    },
    {
        id: 15,
        Name: 'product15',
        price: '87000',
        image: 'image/speaker.jpg',
        cat: 'speaker',
        type: 'new',
    },
    {
        id: 16,
        Name: 'product16',
        price: '52000',
        image: 'image/speaks.jpg',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 17,
        Name: 'product17',
        price: '520',
        image: 'image/b1.jpg',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 18,
        Name: 'product18',
        price: '999',
        image: 'image/b2.png',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 19,
        Name: 'product19',
        price: '899',
        image: 'image/b3.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 20,
        Name: 'product20',
        price: '998',
        image: 'image/b4.jpg',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 21,
        Name: 'product21',
        price: '888',
        image: 'image/b5.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 22,
        Name: 'product22',
        price: '852',
        image: 'image/b6.webp',
        cat: 'bluetooth',
        type: 'new',
    },
    {
        id: 23,
        Name: 'product23',
        price: '520',
        image: 'image/b7.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 24,
        Name: 'product24',
        price: '969',
        image: 'image/b8.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 25,
        Name: 'product25',
        price: '755',
        image: 'image/b9.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 26,
        Name: 'product26',
        price: '960',
        image: 'image/b10.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 27,
        Name: 'product27',
        price: '520',
        image: 'image/b11.jpg',
        cat: 'bluetooth',
        type: 'featured',
    },
    {
        id: 28,
        Name: 'product28',
        price: '852',
        image: 'image/b12.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 29,
        Name: 'product29',
        price: '756',
        image: 'image/b13.jpg',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 30,
        Name: 'product30',
        price: '852',
        image: 'image/b14.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 31,
        Name: 'product31',
        price: '850',
        image: 'image/b15.webp',
        cat: 'bluetooth',
        type: 'top',
    },
    {
        id: 32,
        Name: 'product32',
        price: '300',
        image: 'image/e1.webp',
        cat: 'earphone',
        type: 'top',
    },
    {
        id: 33,
        Name: 'product33',
        price: '400',
        image: 'image/e2.png',
        cat: 'earphone',
        type: 'top',
    },
    {
        id: 34,
        Name: 'product34',
        price: '520',
        image: 'image/e3.png',
        cat: 'earphone',
        type: 'top',
    },
    {
        id: 35,
        Name: 'product35',
        price: '5000',
        image: 'image/h1.jpg',
        cat: 'headphone',
        type: 'top',
    },
    {
        id: 36,
        Name: 'product36',
        price: '963',
        image: 'image/h2.webp',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 37,
        Name: 'product37',
        price: '789',
        image: 'image/h3.webp',
        cat: 'headphone',
        type: 'top',
    },
    {
        id: 38,
        Name: 'product38',
        price: '7411',
        image: 'image/h4.webp',
        cat: 'headphone',
        type: 'top',
    },
    {
        id: 39,
        Name: 'product39',
        price: '852',
        image: 'image/h5.jpg',
        cat: 'headphone',
        type: 'new',
    },
    {
        id: 40,
        Name: 'product40',
        price: '52000',
        image: 'image/l1.jpg',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 41,
        Name: 'product41',
        price: '62000',
        image: 'image/l2.jpg',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 42,
        Name: 'product42',
        price: '96000',
        image: 'image/l3.webp',
        cat: 'laptop',
        type: 'featured',
    },
    {
        id: 43,
        Name: 'product43',
        price: '52999',
        image: 'image/l4.webp',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 44,
        Name: 'product44',
        price: '59999',
        image: 'image/l5.jpg',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 45,
        Name: 'product45',
        price: '96333',
        image: 'image/l7.webp',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 46,
        Name: 'product46',
        price: '95100',
        image: 'image/l8.jpg',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 47,
        Name: 'product47',
        price: '69000',
        image: 'image/l9.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 48,
        Name: 'product48',
        price: '96320',
        image: 'image/l10.jpg',
        cat: 'laptop',
        type: 'top',
    },
    {
        id: 49,
        Name: 'product49',
        price: '52000',
        image: 'image/m1.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 50,
        Name: 'product50',
        price: '72000',
        image: 'image/m2.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 51,
        Name: 'product51',
        price: '7411',
        image: 'image/m3.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 52,
        Name: 'product52',
        price: '8888',
        image: 'image/m4.jpg',
        cat: 'mobile',
        type: 'featured',
    },
    {
        id: 53,
        Name: 'product53',
        price: '9999',
        image: 'image/m5.jpg',
        cat: 'mobile',
        type: 'new',
    },
    {
        id: 54,
        Name: 'product54',
        price: '80000',
        image: 'image/m6.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 55,
        Name: 'product55',
        price: '22000',
        image: 'image/m7.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 56,
        Name: 'product56',
        price: '12000',
        image: 'image/m8.webp',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 57,
        Name: 'product57',
        price: '49999',
        image: 'image/m9.webp',
        cat: 'mobile',
        type: 'featured',
    },
    {
        id: 58,
        Name: 'product58',
        price: '85100',
        image: 'image/m10.jpg',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 60,
        Name: 'product60',
        price: '74100',
        image: 'image/t1.jpg',
        cat: 'tv',
        type: 'top',
    },
    {
        id: 61,
        Name: 'product61',
        price: '52000',
        image: 'image/t2.jpg',
        cat: 'tv',
        type: 'top',
    },
    {
        id: 62,
        Name: 'product62',
        price: '75000',
        image: 'image/t3.webp',
        cat: 'tv',
        type: 'top',
    },
    {
        id: 63,
        Name: 'product63',
        price: '98000',
        image: 'image/t4.jpg',
        cat: 'tv',
        type: 'top',
    },
    {
        id: 64,
        Name: 'product64',
        price: '99999',
        image: 'image/t5.jpg',
        cat: 'tv',
        type: 'top',
    },
    {
        id: 65,
        Name: 'product65',
        price: '52000',
        image: 'image/w1.webp',
        cat: 'watch',
        type: 'featured',
    },
    {
        id: 66,
        Name: 'product66',
        price: '9900',
        image: 'image/w2.webp',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 67,
        Name: 'product67',
        price: '8900',
        image: 'image/w3.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 68,
        Name: 'product68',
        price: '7900',
        image: 'image/w4.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 69,
        Name: 'product69',
        price: '7700',
        image: 'image/w5.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 70,
        Name: 'product70',
        price: '9900',
        image: 'image/w6.webp',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 71,
        Name: 'product71',
        price: '4500',
        image: 'image/w7.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 72,
        Name: 'product72',
        price: '9700',
        image: 'image/w8.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 73,
        Name: 'product73',
        price: '5700',
        image: 'image/w9.jpg',
        cat: 'watch',
        type: 'top',
    },
    {
        id: 74,
        Name: 'product74',
        price: '7777',
        image: 'image/w10.png',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 75,
        Name: 'product75',
        price: '85100',
        image: 'image/m11.webp',
        cat: 'mobile',
        type: 'new',
    },
    {
        id: 76,
        Name: 'product76',
        price: '75100',
        image: 'image/m12.avif',
        cat: 'mobile',
        type: 'top',
    },
    {
        id: 77,
        Name: 'product77',
        price: '8100',
        image: 'image/m13.webp',
        cat: 'mobile',
        type: 'top',
    },

]

export default Homeproduct;